### ISSUE TITLE
Queues are not respected

### ISSUE THREAD

**Issue by PatrickBig** [Hangfire-Mongo/Hangfire.Mongo#290] opened 2021-09-17 15:55 UTC
Agents will run any job regardless of queue.

I tried writing a job filter to overcome this issue but I think this is a larger problem. This is related to #289 

Example:

I have two processing queues:
* default
* mongosh

I have two agents running. One agent is ONLY listening to the "default" queue and the other is only listening to the "reporting" queue.

Agents will attempt to pick up jobs in the "default" queue even if they are a "mongosh" queue member only.

I have defined these queues because some agents have software installed that is required by specific jobs. So when an agent picks up a job incorrectly this can cause spectacular failures.

**Comment by gottscj** [comment] 2021-09-18 11:12
Hi @PatrickBig,

Thanks for posting.

Let me try to reproduce.

**Comment by gottscj** [comment] 2021-09-18 12:46
I cannot reproduce your issue, here is the code I used.
I ran one producer process and two consumer1 processes where each consumer1 process was listening to a specific queue specified in input args.
Does the setup mirror yours? 

[github_issue.zip](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/7189892/github_issue.zip)

**Comment by PatrickBig** [comment] 2021-09-18 13:32
Yeah, it seems pretty similar.

I'm hosting on an ASP.NET platform though and using dependency injection. I can't imagine that would matter.

When I get back to work on Monday I'll grab my startup code for the two queues and see if there is anything odd that sticks out.

**Comment by gottscj** [comment] 2021-09-18 18:50
If your jobs need to run a specific queue, you need to apply the [Queue("mongosh")] (or whatever queue you need) attribute to the given job. Else it will be run on the "default". The producer needs this information as this data will be added to the job meta data

**Comment by gottscj** [comment] 2021-09-18 19:16
I have a v0.7.25 release ready, please let me know your findings on Monday. If I need to fix something I can add it to that release.

**Comment by PatrickBig** [comment] 2021-09-18 19:22
> If your jobs need to run a specific queue, you need to apply the [Queue("mongosh")] (or whatever queue you need) attribute to the given job. Else it will be run on the "default". The producer needs this information as this data will be added to the job meta data

Yes, I was applying the [Queue("mongosh")] attribute to my jobs that needed that queue.

**Comment by gottscj** [comment] 2021-09-18 19:23
ok, 

I will update my test setup to use the attributes

**Comment by gottscj** [comment] 2021-09-18 19:51
Result is the same. I cannot reproduce.
Please make sure your consumers are configured like this:

default:
```csharp
services.AddHangfireServer(options =>
{
    options.Queues = new[] {"default"};
});
```
mongosh:
```csharp
services.AddHangfireServer(options =>
{
    options.Queues = new[] {"mongosh"};
});
```

**Comment by gottscj** [comment] 2021-09-20 15:22
@PatrickBig,

Do you have any updates on this?

Thanks!

**Comment by PatrickBig** [comment] 2021-09-20 15:44
Yes, I'm still having the problem.

I spent some more time this morning digging.


I have two consumers that are configured to process different queues.

Agent 1 (default only):
```csharp
services.AddHangfire(config => config
                    .UseConsole()
                    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                    .UseSimpleAssemblyNameTypeSerializer()
                    .UseRecommendedSerializerSettings()
                    .UseMongoStorage(mongoClient.MongoClient, mongoClient.DatabaseName, new MongoStorageOptions
                    {
                        MigrationOptions = new MongoMigrationOptions
                        {
                            MigrationStrategy = new MigrateMongoMigrationStrategy(),
                            BackupStrategy = new CollectionMongoBackupStrategy(),
                        },
                        Prefix = "hangfire",
                        CheckConnection = false,
                    }));
services.AddHangfireServer();
```

Agent 2 (mongosh only):
```csharp
services.AddHangfire(config => config
                    .UseConsole()
                    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                    .UseSimpleAssemblyNameTypeSerializer()
                    .UseRecommendedSerializerSettings()
                    .UseMongoStorage(mongoClient.MongoClient, mongoClient.DatabaseName, new MongoStorageOptions
                    {
                        MigrationOptions = new MongoMigrationOptions
                        {
                            MigrationStrategy = new MigrateMongoMigrationStrategy(),
                            BackupStrategy = new CollectionMongoBackupStrategy(),
                        },
                        Prefix = "hangfire",
                        CheckConnection = false,
                    }));

services.AddHangfireServer(options =>
            {
                options.Queues = new string[] { "mongosh" };
            });
```


Jobs are being consumed by either queue regardless of the jobs setting.

Job1:
```csharp
[Queue("default")]
public void QueueTest()
{
    Console.WriteLine("This is a job test for default");
}

// Startup code:
RecurringJob.AddOrUpdate<DefaultQueueTesting>(c => c.QueueTest(), "*/3 * * * *");

// Just queue it
BackgroundJobClient.Enqueue<DefaultQueueTesting>(c => c.QueueTest());
```

I'll see this job get picked up by my "mongosh" agent.


Same for mongosh

Job2:
```csharp
[Queue("mongosh")]
public void QueueTest()
{
    Console.WriteLine("This is a job test for mongosh");
}

// Startup code:
RecurringJob.AddOrUpdate<MongoShellQueueTesting>(c => c.QueueTest(), "*/3 * * * *");

// Just queue it
BackgroundJobClient.Enqueue<MongoShellQueueTesting>(c => c.QueueTest());
```


Both agents are consuming both jobs regardless of the queue attribute

**Comment by gottscj** [comment] 2021-09-20 15:53
hmm, 

Everything looks OK to me. 

Could you try to:

create two different classes, add the QueueAttribute on class level.

explicitly configure the queue on agent1 to "default" in your call to services.AddHangfireService.

Thanks.

**Comment by PatrickBig** [comment] 2021-09-20 16:45
I did decorate at the class level with the `Queue` attribute and added the `default` queue to the startup of the other agent. 

Same results.

I can't really share my setup as it's a bit too large.

**Comment by gottscj** [comment] 2021-09-20 17:24
ok, thanks,

Could you try to create separate projects reproducing. You could alter the projects I added earlier?

**Comment by gottscj** [comment] 2021-09-20 19:27
I tried updating the src to run an aspnet core app with DI, same as you posted.
Could you try this?

[github_issue-2.zip](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/7198222/github_issue-2.zip)

**Comment by PatrickBig** [comment] 2021-09-20 19:43
I can't reproduce it outside of my project. So it's clearly some bug within my system. I'll have to keep digging.

This is the project I created to simulate the issue.... which is kind of useless since I can't reproduce it.
[HangfireIssues.zip](https://github.com/sergeyzwezdin/Hangfire.Mongo/files/7198317/HangfireIssues.zip)

**Comment by gottscj** [comment] 2021-09-20 19:46
ok, lets keep digging then. I'll create the v0.7.25 release, and if we find something I will release fix for that.

**Comment by gottscj** [comment] 2021-10-01 14:55
@PatrickBig,

Did you have any luck resolving this?

**Closed** 2021-11-09 12:55 UTC
