### ISSUE TITLE
Hangfire is not working for CosmosDB after migrating from MongoDB giving error: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "DuplicateKey", Code : 11000, Message : "E11000 duplicate key error collection: Hangfire

### ISSUE THREAD

**Issue by murtuza3436** [Hangfire-Mongo/Hangfire.Mongo#362] opened 2023-09-06 17:36 UTC
We were using MongoDb in our project and Hangfire was working perfectly fine over there but after we have shifted to CosmosDb Hangfire has stopped working, we are using MongoClient only to connect to CosmosDB by passing CosmosDB connection string to MongoClient everything is fine with this MongoClient object but Hangfire is not working with this. It is creating Hangfire default collections into the CosmosDB and when we are trying to manually execute any of the jobs from Hangfire dashboard it gives us this error:

`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]       An unhandled exception has occurred while executing the request. MongoDB.Driver.MongoBulkWriteException`1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors. WriteErrors: [ { Category : "DuplicateKey", Code : 11000, Message : "E11000 duplicate key error collection: bomHangfire2.core.hangfire.jobGraph. Failed _id or unique index constraint." } ].    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)    at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass30_0.<BulkWrite>b__0(IClientSessionHandle session)    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)    at Hangfire.Mongo.MongoWriteOnlyTransaction.Commit()    at Hangfire.Mongo.MongoConnection.CreateExpiredJob(Job job, IDictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)    at Hangfire.Client.CoreBackgroundJobFactory.<>c__DisplayClass15_0.<CreateBackgroundJobTwoSteps>b__0(Int32 _)    at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action) --- End of stack trace from previous location where exception was thrown ---    at Hangfire.Client.CoreBackgroundJobFactory.RetryOnException[T](Int32& attemptsLeft, Func`2 action)    at Hangfire.Client.CoreBackgroundJobFactory.CreateBackgroundJobTwoSteps(CreateContext context, Dictionary`2 parameters, DateTime createdAt, TimeSpan expireIn)    at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)    at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_0.<CreateWithFilters>b__0()    at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)    at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass12_1.<CreateWithFilters>b__2()    at Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable`1 filters)    at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)    at Hangfire.RecurringJobExtensions.TriggerRecurringJob(IBackgroundJobFactory factory, JobStorage storage, IStorageConnection connection, IProfiler profiler, RecurringJobEntity recurringJob, DateTime now)    at Hangfire.RecurringJobManager.TriggerJob(String recurringJobId)    at Hangfire.RecurringJobManager.Trigger(String recurringJobId)    at Hangfire.Dashboard.DashboardRoutes.<>c.<.cctor>b__6_27(IRecurringJobManager manager, String jobId)    at Hangfire.Dashboard.RouteCollectionExtensions.<>c__DisplayClass4_0.<AddRecurringBatchCommand>b__0(DashboardContext context, String jobId)    at Hangfire.Dashboard.BatchCommandDispatcher.Dispatch(DashboardContext context)    at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`
We have used this code into the Startup.cs file
```

public void ConfigureServices(IServiceCollection services) 
 		{ 
 			services.AddScoped<IMailService, MailService>();
  			services.AddHangfire(config =>
  			{ 
 				var opt = new CosmosStorageOptions
  				{
 					MigrationOptions = new MongoMigrationOptions
  					{
  						BackupStrategy = new NoneMongoBackupStrategy(),
 						MigrationStrategy = new DropMongoMigrationStrategy(), 
 					},
  					Prefix = "job.hangfire", 
 				}; 
 				var mongoClient = new MongoClient(Configuration.GetConnectionString("DefaultConnection")); 
 				GlobalConfiguration.Configuration.UseCosmosStorage(mongoClient, "Hangfire", opt); 
 			});  
			services.AddHangfireServer(serverOptions =>
  			{ 
 				serverOptions.ServerName = AppSettings.Environment.CurrentServer;
  			});
   			} 

public void Configure(IApplicationBuilder app, IWebHostEnvironment env) 
 		{ 
 						app.UseEndpoints(endpoints => 
 			{  
				endpoints.MapRazorPages();
 				endpoints.MapHangfireDashboard("/jobs", new DashboardOptions{});
  			});
 			RecurringJob.AddOrUpdate<IMailService>("sendEmails", h => h.SendMails(), $"0 1 * * *"); 
 		} 
}

```
And we have Our method SendMails() which is sending mail.

Problem is that hangifre.jobgraph table is not handled by us and hangfire only inserts and updates that table and in cosmos _id key is made unique by default, so, how can we fix this issue.

**Comment by gottscj** [comment] 2023-09-19 20:09
Hi @murtuza3436,

unfortunately I dont currently have access to a CosmosDB instance and the emulator is working very well. Is it a completely new setup? so there is nothing in the DB. It could be CosmosDB is not supporting Bulkwrites?

I will see if I cant get access to a CosmosDB instance. 
Thanks

**Comment by gottscj** [comment] 2023-09-19 20:11
Oh I see you have migrated from Mongo. Maybe try a fresh start?

out of curiosity. Why did you change to CosmosDB?

Thanks

**Comment by murtuza3436** [comment] 2023-09-20 05:47
Yes, you can try and check it, it is giving error in Bulkwrites operation. Can you try it bit fast as I am stuck it in since last 20 days and I need it little urgently.
I tried it with a fresh installation as well but it is giving error in that as well.
In project I am working needs CosmosDB, so I migrated to that

**Comment by gottscj** [comment] 2023-09-20 05:53
@murtuza3436,

ok I see. I will prioritize this. :) 

You can also try https://github.com/imranmomin/Hangfire.AzureCosmosDb. It hasnt had any commits for a while, so im not sure its still maintained.

**Comment by gottscj** [comment] 2023-09-20 17:35
@murtuza3436,

I have gained access to a CosmosDB instance and I can reproduce your issue.

However I do not yet understand why its throwing an duplicate key error. the _id is definitely not the same. I do have another unique index for a field "Key" Its fine for Mongo if the document does not have that field, but it might trigger something in cosmosdb. I will try to figure out what is going on.
if you can, you should consider the above link. its with the SQL driver however.

**Comment by murtuza3436** [comment] 2023-09-21 11:26
I have tried with Hangfire.AzureCosmosDb as well that is also not working

**Comment by MrKingEd** [comment] 2023-09-21 11:46
I've been following this conversation since yesterday or so. I was facing the exact same issue. I tried the latest fix that was submitted to the cosmosdb branch yesterday and that seemed to fix the problem for me. (Hangfire.AzureCosmosDb also wasn't working for me). Thanks @gottscj !

**Comment by murtuza3436** [comment] 2023-09-21 11:54
Thanks @gottscj for the fix. This changes are also working for me as well, you can merge this change into master and can create a package with this code, if no other issues are there from your side.

**Comment by gottscj** [comment] 2023-09-21 21:18
@murtuza3436 , @MrKingEd,

Thank you for testing this. I only have access to a free tier, so its somewhat limited what I can test.

I have just released v1.9.10 which should address your issues.

Please test this **_thoroughly_** in your setup before using this in any production environments! My tests has been quite limited!

Please also create a new issue if you experience issues in your findings, but you are most welcome to supply feedback in this thread if you are successfully using it.

Thanks!

**Comment by murtuza3436** [comment] 2023-09-22 09:19
@gottscj 
Thank you so much for the prompt response, and resolving the issue. 
Sure, we will test it thoroughly and will provide feedback regarding that as well.

Thanks!

**Comment by gottscj** [comment] 2023-10-03 19:04
closing.. please feel free to comment in this issue with feedback

**Closed by gottscj** 2023-10-03 19:04 UTC
